"""Generate exact SQLAlchemy models from the rich legacy schema JSON.

Output: backend/models_legacy_exact.py  (self-contained, own Base/MetaData).
This is the canonical, byte-for-byte representation of the legacy Access schema.
"""
import json
import re
from pathlib import Path

RICH = json.load(
    open(r"c:\Users\Dell\Desktop\star-hms\_legacy\extracted\mdb_schema_rich.json", encoding="utf-8")
)
OUT = Path(r"c:\Users\Dell\Desktop\star-hms\backend\models_legacy_exact.py")

# Access type -> (SQLAlchemy ctor, needs_length)
TYPE_MAP = {
    "BOOLEAN": ("Boolean", False),
    "BYTE": ("SmallInteger", False),
    "INTEGER": ("SmallInteger", False),
    "LONG": ("Integer", False),
    "CURRENCY": ("Numeric(19, 4)", False),
    "SINGLE": ("Float", False),
    "DOUBLE": ("Float", False),
    "DATETIME": ("DateTime", False),
    "BINARY": ("LargeBinary", False),
    "OLE": ("LargeBinary", False),
    "MEMO": ("Text", False),
    "TEXT": ("String", True),
    "GUID": ("String(38)", False),
    "BIGINT": ("BigInteger", False),
    "NUMERIC": ("Numeric(28, 6)", False),
}


def cls_name(tbl: str) -> str:
    # keep table name as-is for class; ensure valid identifier
    return re.sub(r"\W", "_", tbl)


def col_line(col, pk_names):
    name = col["name"]
    atype = col["type"]
    sa, needs_len = TYPE_MAP.get(atype, ("String", True))
    if needs_len:
        length = col.get("length") or 255
        # Access stores text length in bytes; Jet unicode = 2 bytes/char
        chars = max(1, int(length) // 2) if length and length > 1 else length
        sa = f"String({chars})"
    args = [sa]
    is_pk = name in pk_names
    if is_pk:
        args.append("primary_key=True")
        if col.get("autonumber"):
            args.append("autoincrement=True")
    if not is_pk and not col.get("nullable", True):
        args.append("nullable=False")
    return f'    {name} = Column("{name}", {", ".join(args)})'


def main():
    lines = [
        '"""AUTO-GENERATED from legacy Access .Mdb schema. Do not edit by hand.',
        "",
        "Exact representation of the legacy STAR-HMS database (275 tables).",
        'Generated by scratch_gen_models.py from _legacy/extracted/mdb_schema_rich.json."""',
        "from sqlalchemy import (",
        "    Column, Integer, SmallInteger, BigInteger, String, Text, Boolean,",
        "    DateTime, Float, Numeric, LargeBinary,",
        ")",
        "from sqlalchemy.orm import declarative_base",
        "",
        "LegacyBase = declarative_base()",
        "Base = LegacyBase  # alias",
        "",
    ]
    # group by source file for readability
    by_file = {}
    for tbl, meta in RICH.items():
        by_file.setdefault(meta["file"], []).append(tbl)

    for fname in sorted(by_file):
        lines.append(f"\n# {'='*70}\n# Source: {fname}\n# {'='*70}")
        for tbl in sorted(by_file[fname]):
            meta = RICH[tbl]
            pk_names = set(meta.get("pk") or [])
            cols = meta["columns"]
            # ensure at least one PK for SQLAlchemy; else synthesize on first col
            if not (pk_names & {c["name"] for c in cols}):
                pk_names = {cols[0]["name"]}
            lines.append(f"\n\nclass {cls_name(tbl)}(LegacyBase):")
            lines.append(f'    __tablename__ = "{tbl}"')
            for c in cols:
                lines.append(col_line(c, pk_names))
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} with {len(RICH)} tables")


if __name__ == "__main__":
    main()
