import React from 'react';

interface PrintHeaderProps {
  hospitalName?: string;
  address?: string;
  contact?: string;
  title: string;
}

export const PrintHeader: React.FC<PrintHeaderProps> = ({ 
  hospitalName = "Star Hospital", 
  address = "123 Healthcare Ave, City", 
  contact = "Ph: (555) 123-4567",
  title 
}) => (
  <div className="text-center border-b-2 border-gray-800 pb-4 mb-4">
    <h1 className="text-2xl font-bold uppercase tracking-wider">{hospitalName}</h1>
    <p className="text-sm text-gray-600">{address}</p>
    <p className="text-sm text-gray-600">{contact}</p>
    <h2 className="text-xl font-bold mt-4 underline decoration-double">{title}</h2>
  </div>
);

interface PatientDemographicsProps {
  patient: {
    name: string;
    ageGender?: string;
    mobile?: string;
    regNo?: string | number;
    address?: string;
    doctor?: string;
    date: string;
    refBy?: string;
  };
}

export const PrintPatientDemographics: React.FC<PatientDemographicsProps> = ({ patient }) => (
  <div className="grid grid-cols-2 gap-4 text-sm mb-6 p-4 border border-medical-border rounded-md">
    <div>
      <p><span className="font-semibold">Patient Name:</span> {patient.name}</p>
      <p><span className="font-semibold">Age/Gender:</span> {patient.ageGender || 'N/A'}</p>
      <p><span className="font-semibold">Mobile:</span> {patient.mobile || 'N/A'}</p>
      <p><span className="font-semibold">Address:</span> {patient.address || 'N/A'}</p>
    </div>
    <div>
      <p><span className="font-semibold">Date:</span> {patient.date}</p>
      <p><span className="font-semibold">Reg. No:</span> {patient.regNo || 'N/A'}</p>
      <p><span className="font-semibold">Consulting Doctor:</span> {patient.doctor || 'N/A'}</p>
      <p><span className="font-semibold">Referred By:</span> {patient.refBy || 'Self'}</p>
    </div>
  </div>
);

interface PrintTableProps {
  columns: { header: string; accessor: string; align?: 'left' | 'right' | 'center' }[];
  data: any[];
}

export const PrintTable: React.FC<PrintTableProps> = ({ columns, data }) => (
  <table className="w-full text-sm mb-6 border-collapse">
    <thead>
      <tr className="border-b-2 border-gray-800">
        {columns.map((col, idx) => (
          <th key={idx} className={`py-2 text-${col.align || 'left'} font-semibold`}>
            {col.header}
          </th>
        ))}
      </tr>
    </thead>
    <tbody>
      {data.map((row, rowIdx) => (
        <tr key={rowIdx} className="border-b border-medical-border">
          {columns.map((col, colIdx) => (
            <td key={colIdx} className={`py-2 text-${col.align || 'left'}`}>
              {row[col.accessor]}
            </td>
          ))}
        </tr>
      ))}
    </tbody>
  </table>
);

interface PrintFooterProps {
  totals: { label: string; value: string | number }[];
  amountInWords?: string;
  generatedBy?: string;
}

export const PrintFooter: React.FC<PrintFooterProps> = ({ totals, amountInWords, generatedBy = "System Admin" }) => (
  <div className="border-t-2 border-gray-800 pt-4 mt-8 page-break-inside-avoid">
    <div className="flex justify-between">
      <div className="w-1/2">
        {amountInWords && (
          <p className="text-sm italic mb-8">Amount in words: {amountInWords}</p>
        )}
        <div className="mt-8">
          <p className="text-sm font-semibold border-t border-gray-400 inline-block pt-1">Authorized Signatory</p>
        </div>
      </div>
      <div className="w-1/3">
        {totals.map((t, idx) => (
          <div key={idx} className={`flex justify-between py-1 ${idx === totals.length - 1 ? 'font-bold border-t border-gray-400 mt-1 pt-2' : ''}`}>
            <span>{t.label}:</span>
            <span>₹{t.value}</span>
          </div>
        ))}
      </div>
    </div>
    <div className="mt-8 text-xs text-center text-gray-500">
      <p>Generated by {generatedBy} on {new Date().toLocaleString()}</p>
      <p>This is a computer generated document.</p>
    </div>
  </div>
);

interface PrintLayoutProps {
  children: React.ReactNode;
  id?: string;
}

export const PrintLayout: React.FC<PrintLayoutProps> = ({ children, id = "print-section" }) => {
  return (
    <div 
      id={id} 
      className="hidden print:block absolute top-0 left-0 w-full h-auto bg-white text-black p-8 text-left z-50 print-only-section"
      style={{ minHeight: '100vh' }}
    >
      {children}
    </div>
  );
};

