import React from 'react';
import { format } from 'date-fns';
import { Printer } from 'lucide-react';

interface ReportViewerProps {
  title: string;
  subtitle?: string;
  dateRange?: { start: string; end: string };
  children: React.ReactNode;
  onPrint?: () => void;
}

export function ReportViewer({ title, subtitle, dateRange, children, onPrint }: ReportViewerProps) {
  const handlePrint = () => {
    if (onPrint) {
      onPrint();
    } else {
      window.print();
    }
  };

  return (
    <div className="flex flex-col h-full bg-gray-50">
      {/* Non-printable Control Bar */}
      <div className="print:hidden bg-white border-b border-gray-200 px-6 py-4 flex justify-between items-center sticky top-0 z-10 shadow-sm">
        <div>
          <h2 className="text-xl font-bold text-gray-800">{title}</h2>
          {subtitle && <p className="text-sm text-gray-500">{subtitle}</p>}
        </div>
        <button 
          onClick={handlePrint}
          className="btn-primary flex items-center gap-2"
        >
          <Printer size={18} />
          Print Report
        </button>
      </div>

      {/* Printable Area - A4 aspect ratio approx wrapper for screen viewing */}
      <div className="flex-1 overflow-auto p-8 print:p-0">
        <div className="max-w-5xl mx-auto bg-white shadow-lg print:shadow-none min-h-[29.7cm] print:min-h-0 print:w-full">
          
          {/* Standardized Print Header */}
          <div className="hidden print:block text-center border-b-2 border-gray-800 pb-4 mb-6">
            <h1 className="text-3xl font-bold text-gray-900 tracking-tight uppercase">STAR HMS</h1>
            <h2 className="text-xl font-semibold text-gray-800 mt-2">{title}</h2>
            {subtitle && <h3 className="text-md text-gray-600 mt-1">{subtitle}</h3>}
            {dateRange && (
              <p className="text-sm text-gray-600 mt-2 font-medium">
                Period: {format(new Date(dateRange.start), 'dd MMM yyyy')} to {format(new Date(dateRange.end), 'dd MMM yyyy')}
              </p>
            )}
            <p className="text-xs text-gray-500 mt-1">
              Printed on: {format(new Date(), 'dd MMM yyyy HH:mm:ss')}
            </p>
          </div>

          {/* Report Content */}
          <div className="p-8 print:p-0">
            {children}
          </div>

          {/* Standardized Print Footer */}
          <div className="hidden print:flex justify-between items-end border-t border-gray-300 mt-12 pt-4 text-sm text-gray-600">
            <div>
              <p>Generated by: System</p>
            </div>
            <div>
              <p>Authorized Signatory</p>
              <div className="h-12 w-48 border-b border-dashed border-gray-400 mt-4"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
