# Re-export all schemas from the flat schemas.py for backward compatibility.
from backend.schemas_flat import (
    UserBase, UserCreate, UserLogin, UserResponse,
    Token, TokenData,
    PatientCategoryBase, PatientCategoryCreate, PatientCategoryResponse,
    PatientBase, PatientCreate, PatientResponse,
    DoctorCategoryBase, DoctorCategoryCreate, DoctorCategoryResponse,
    DoctorRoleBase, DoctorRoleCreate, DoctorRoleResponse,
    DoctorBase, DoctorCreate, DoctorResponse,
    FloorBase, FloorCreate, FloorResponse,
    WardBase, WardCreate, WardResponse,
    BedBase, BedCreate, BedResponse,
    ServiceGroupBase, ServiceGroupCreate, ServiceGroupResponse,
    ServiceBase, ServiceCreate, ServiceResponse,
    OPDRegistrationBase, OPDRegistrationCreate, OPDRegistrationResponse,
    OPDBillCreate, OPDBillResponse,
    IPDAdmissionBase, IPDAdmissionCreate, IPDAdmissionResponse,
    IPDBillCreate, IPDBillResponse,
    DashboardStats,
    # Payroll
    PayDeptBase, PayDeptCreate, PayDeptResponse,
    PayDesnBase, PayDesnCreate, PayDesnResponse,
    PayEmpBase, PayEmpCreate, PayEmpResponse,
    # New masters
    RefCatgBase, RefCatgCreate, RefCatgResponse,
    RefByBase, RefByCreate, RefByResponse,
    RefToBase, RefToCreate, RefToResponse,
    StationBase, StationCreate, StationResponse,
    AreaBase, AreaCreate, AreaResponse,
    PartyGroupBase, PartyGroupCreate, PartyGroupResponse,
    PartyBase, PartyCreate, PartyResponse,
    ProductGroupBase, ProductGroupCreate, ProductGroupResponse,
    ProductBase, ProductCreate, ProductResponse,
    # Diagnosis
    DiagBase, DiagCreate, DiagResponse,
)

__all__ = [
    "UserBase", "UserCreate", "UserLogin", "UserResponse",
    "Token", "TokenData",
    "PatientCategoryBase", "PatientCategoryCreate", "PatientCategoryResponse",
    "PatientBase", "PatientCreate", "PatientResponse",
    "DoctorCategoryBase", "DoctorCategoryCreate", "DoctorCategoryResponse",
    "DoctorRoleBase", "DoctorRoleCreate", "DoctorRoleResponse",
    "DoctorBase", "DoctorCreate", "DoctorResponse",
    "FloorBase", "FloorCreate", "FloorResponse",
    "WardBase", "WardCreate", "WardResponse",
    "BedBase", "BedCreate", "BedResponse",
    "ServiceGroupBase", "ServiceGroupCreate", "ServiceGroupResponse",
    "ServiceBase", "ServiceCreate", "ServiceResponse",
    "OPDRegistrationBase", "OPDRegistrationCreate", "OPDRegistrationResponse",
    "OPDBillCreate", "OPDBillResponse",
    "IPDAdmissionBase", "IPDAdmissionCreate", "IPDAdmissionResponse",
    "IPDBillCreate", "IPDBillResponse",
    "DashboardStats",
    # Payroll
    "PayDeptBase", "PayDeptCreate", "PayDeptResponse",
    "PayDesnBase", "PayDesnCreate", "PayDesnResponse",
    "PayEmpBase", "PayEmpCreate", "PayEmpResponse",
    # New masters
    "RefCatgBase", "RefCatgCreate", "RefCatgResponse",
    "RefByBase", "RefByCreate", "RefByResponse",
    "RefToBase", "RefToCreate", "RefToResponse",
    "StationBase", "StationCreate", "StationResponse",
    "AreaBase", "AreaCreate", "AreaResponse",
    "PartyGroupBase", "PartyGroupCreate", "PartyGroupResponse",
    "PartyBase", "PartyCreate", "PartyResponse",
    "ProductGroupBase", "ProductGroupCreate", "ProductGroupResponse",
    "ProductBase", "ProductCreate", "ProductResponse",
    # Diagnosis
    "DiagBase", "DiagCreate", "DiagResponse",
]
