from pydantic import BaseModel
from typing import Optional, List
from datetime import date

# -----------------------------------
# Outpatient Registration (OutdReg)
# -----------------------------------
class OutdRegBase(BaseModel):
    OpgDate: date
    OpgPttCode: int
    OpgCDctCode: Optional[int] = None
    OpgRByCode: Optional[int] = None
    OpgRToCode: Optional[int] = None
    OpgPDigCode: Optional[int] = None
    OpgSrvCode: Optional[int] = None
    OpgUnit: float = 1.0
    OpgRate: float = 0.0
    OpgAmtBefDisc: float = 0.0
    OpgDiscPer: float = 0.0
    OpgDiscAmt: float = 0.0
    OpgAmtAftDisc: float = 0.0
    OpgRemark: Optional[str] = None
    OpgRecState: int = 1
    OpgRfugAmt: float = 0.0

class OutdRegCreate(OutdRegBase):
    pass # OpgVchNo will be auto-generated by the backend

class OutdRegUpdate(OutdRegBase):
    pass

class OutdRegResponse(OutdRegBase):
    OpgCode: int
    OpgVchNo: int
    
    class Config:
        from_attributes = True

# -----------------------------------
# Outpatient Billing (OutdHdr & OutdBill)
# -----------------------------------
class OutdBillBase(BaseModel):
    ObdSrvCode: Optional[int] = None
    ObdSno: Optional[int] = None
    ObdUnit: float = 1.0
    ObdRate: float = 0.0
    ObdAmtBefDisc: float = 0.0
    ObdDiscPer: float = 0.0
    ObdDiscAmt: float = 0.0
    ObdAmtAftDisc: float = 0.0

class OutdBillCreate(OutdBillBase):
    pass

class OutdBillResponse(OutdBillBase):
    ObdCode: int
    ObdOhdCode: int
    
    class Config:
        from_attributes = True

class OutdHdrBase(BaseModel):
    OhdDate: date
    OhdPttCode: int
    OhdCDctCode: Optional[int] = None
    OhdRByCode: Optional[int] = None
    OhdBillType: Optional[str] = None
    OhdTotalAmt: float = 0.0
    OhdDiscPer: float = 0.0
    OhdDiscAmt: float = 0.0
    OhdDepAmt: float = 0.0
    OhdBalAmt: float = 0.0
    OhdRfugAmt: float = 0.0
    OhdRemark: Optional[str] = None

class OutdHdrCreate(OutdHdrBase):
    details: List[OutdBillCreate]

class OutdHdrResponse(OutdHdrBase):
    OhdCode: int
    OhdVchNo: int
    
    class Config:
        from_attributes = True

# -----------------------------------
# Unified Payment / Refund Requests
# -----------------------------------
from enum import Enum

class OpdTransactionType(str, Enum):
    RECEIPT = 'receipt'
    BILL = 'bill'
    REGISTRATION = 'registration'

class OpdPaymentRequest(BaseModel):
    transaction_type: OpdTransactionType
    ref_id: int
    amount: float
    date: date

class OpdRefundRequest(BaseModel):
    transaction_type: OpdTransactionType
    ref_id: int
    amount: float
    date: date


# -----------------------------------
# OPD Receipt (OutdRcpt)
# -----------------------------------
class OutdRcptBase(BaseModel):
    OrcDate: date
    OrcPttCode: int
    OrcCDctCode: Optional[int] = None
    OrcRByCode: Optional[int] = None
    OrcReceiptType: Optional[str] = None
    OrcDiscPer: float = 0.0
    OrcTotalAmt: float = 0.0
    OrcRecvdAmt: float = 0.0
    OrcRfugAmt: float = 0.0
    OrcBalAmt: float = 0.0
    OrcAdvAmt: float = 0.0
    OrcRemark: Optional[str] = None
    OrcVoidFlag: bool = False
    OrcRecState: int = 1

class OutdRcptCreate(OutdRcptBase):
    pass

class OutdRcptResponse(OutdRcptBase):
    OrcCode: int
    OrcVchNo: int
    
    class Config:
        from_attributes = True

# -----------------------------------
# OPD Doctor Shares & Payments
# -----------------------------------
class OutdRcDctDtlBase(BaseModel):
    OrdOrcCode: int
    OrdDctCode: Optional[int] = None
    OrdSharePer: float = 0.0
    OrdRecState: int = 1

class OutdBlDctDtlBase(BaseModel):
    OddOhdCode: int
    OddDctCode: Optional[int] = None
    OddSharePer: float = 0.0
    OddShareAmt: float = 0.0
    OddRecState: int = 1

class OutdPymtHdrBase(BaseModel):
    OphOrcCode: Optional[int] = None
    OphDate: date
    OphAmt: float = 0.0
    OphRecState: int = 1

class OutdRefdHdrBase(BaseModel):
    OrhOrcCode: Optional[int] = None
    OrhDate: date
    OrhAmt: float = 0.0
    OrhRecState: int = 1

class OutdBlPymtHdrBase(BaseModel):
    ObpOhdCode: Optional[int] = None
    ObpDate: date
    ObpAmt: float = 0.0
    ObpRecState: int = 1

class OutdBlRefdHdrBase(BaseModel):
    ObrOhdCode: Optional[int] = None
    ObrDate: date
    ObrAmt: float = 0.0
    ObrRecState: int = 1

class OutdRgRefdBase(BaseModel):
    OrrOpgCode: Optional[int] = None
    OrrDate: date
    OrrAmt: float = 0.0
    OrrRecState: int = 1
