from pydantic import BaseModel
from typing import Optional, List
from datetime import date

# -----------------------------------
# Outpatient Registration (OutdReg)
# -----------------------------------
class OutdRegBase(BaseModel):
    OpgDate: date
    OpgPttCode: int
    OpgCDctCode: Optional[int] = None
    OpgRByCode: Optional[int] = None
    OpgRToCode: Optional[int] = None
    OpgPDigCode: Optional[int] = None
    OpgSrvCode: Optional[int] = None
    OpgUnit: float = 1.0
    OpgRate: float = 0.0
    OpgAmtBefDisc: float = 0.0
    OpgDiscPer: float = 0.0
    OpgDiscAmt: float = 0.0
    OpgAmtAftDisc: float = 0.0
    OpgRemark: Optional[str] = None
    OpgRecState: int = 1

class OutdRegCreate(OutdRegBase):
    pass # OpgVchNo will be auto-generated by the backend

class OutdRegUpdate(OutdRegBase):
    pass

class OutdRegResponse(OutdRegBase):
    OpgCode: int
    OpgVchNo: int
    
    class Config:
        from_attributes = True

# -----------------------------------
# Outpatient Billing (OutdHdr & OutdBill)
# -----------------------------------
class OutdBillBase(BaseModel):
    ObdSrvCode: Optional[int] = None
    ObdSno: Optional[int] = None
    ObdUnit: float = 1.0
    ObdRate: float = 0.0
    ObdAmtBefDisc: float = 0.0
    ObdDiscPer: float = 0.0
    ObdDiscAmt: float = 0.0
    ObdAmtAftDisc: float = 0.0

class OutdBillCreate(OutdBillBase):
    pass

class OutdBillResponse(OutdBillBase):
    ObdCode: int
    ObdOhdCode: int
    
    class Config:
        from_attributes = True

class OutdHdrBase(BaseModel):
    OhdDate: date
    OhdPttCode: int
    OhdCDctCode: Optional[int] = None
    OhdRByCode: Optional[int] = None
    OhdBillType: Optional[str] = None
    OhdTotalAmt: float = 0.0
    OhdDiscPer: float = 0.0
    OhdDiscAmt: float = 0.0
    OhdDepAmt: float = 0.0
    OhdBalAmt: float = 0.0
    OhdRemark: Optional[str] = None

class OutdHdrCreate(OutdHdrBase):
    details: List[OutdBillCreate]

class OutdHdrResponse(OutdHdrBase):
    OhdCode: int
    OhdVchNo: int
    
    class Config:
        from_attributes = True

# -----------------------------------
# Unified Payment / Refund Requests
# -----------------------------------
from enum import Enum

class OpdTransactionType(str, Enum):
    RECEIPT = 'receipt'
    BILL = 'bill'
    REGISTRATION = 'registration'

class OpdPaymentRequest(BaseModel):
    transaction_type: OpdTransactionType
    ref_id: int
    amount: float
    date: date

class OpdRefundRequest(BaseModel):
    transaction_type: OpdTransactionType
    ref_id: int
    amount: float
    date: date
